### PR TITLE
Bootstrap upgrade, category plugin, annotation sortability

### PR DESCRIPTION
**Pull request by stephskardal**
(3 commits)
- needs migration applied for category work

### CODE REVIEW

**Comment by stephskardal** [comment]
I realize now I should have put the two JS plugins (xcolor + colorpicker) in vendor/assets/javascripts, so that fix will come in a later commit.

**Comment by stephskardal** [comment]
Added a couple more commits with category filtering in rightnav.

**Comment by jamiefolsom** [comment]
Hi Steph,

This looks great. One request. What do you think about adding in a config variable, so that both the categorization UI, and the custom ordering UI could be switched off if they're not desired? 

Have a look at [this PR](https://github.com/performant-software/Annotation-Studio/commit/d737654e57d3d148c9cbef5d67010f342ce2753a) for an example.

Let me know what you think. I am testing this on a staging server now.

Thanks!

Jamie

**Comment by stephskardal** [comment]
Hi Jamie - config variables for both sort & categories added & PR updated to include these. Also included is category filtering in the right nav. Note: category filtering not working as expected in public_documents, but there were other issues there that were not related to my work that were preventing /api/search from working at all in public_documents, so that may be something to discuss.

**Pull request closed without merging**
